services:
  mothership:
    container_name: mothership
    networks:
      - mothership-core
    build:
      context: ./fleet_beacon
      args:
        MODEL_NAME: ${MODEL_NAME}
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    env_file:
      - ./.env
      - ./fleet_beacon/.env
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"
    volumes:
      - ./stargate:/stargate
    mem_limit: 8g
    memswap_limit: 8g 
    restart: unless-stopped
  high-templar:
    image: ${DB_VERSION}
    container_name: high-templar
    networks:
      - mothership-core
    env_file:
      - ./.env
      - ./templar_archives/.env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./templar_archives/stasis_ward:${DB_VOLUME:-/stasis_ward}
    mem_limit: 2g
    restart: unless-stopped
  tempest:
    container_name: tempest
    networks:
      - mothership-core
    build: ./assimilator
    env_file:
      - ./.env
      - ./assimilator/.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./assimilator/redis.conf:/usr/local/etc/redis/redis.conf
    depends_on:
      - mothership # check conditions and health checks
      - high-templar
    mem_limit: 2g
    restart: unless-stopped
  sentry:
    container_name: sentry
    networks:
      - mothership-core
    build:
      context: .
      dockerfile: cybernetics_core/Dockerfile
    env_file:
      - .env
      - cybernetics_core/.env
    volumes:
      - ./.env:/carrier/.env:ro
      - ./cybernetics_core:/carrier/cybernetics_core:rw
      - ./pylon:/carrier/pylon
      - ./stargate:/stargate
      - ./stargate/warp_gate:/stargate/warp_gate
    working_dir: /carrier
    depends_on:
      - tempest
    mem_limit: 1g
    restart: unless-stopped
  zealot:
    container_name: zealot
    networks:
      - mothership-core
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - ./.env
      - ./gateway/.env
    volumes:
      - ./.env:/carrier/.env:ro
      - ./gateway:/carrier/gateway:rw
      - ./pylon:/carrier/pylon
    depends_on:
      - tempest
    mem_limit: 1g
    restart: unless-stopped
  stalker:
    container_name: stalker
    networks:
      - mothership-core
    build:
      context: .
      dockerfile: twilight_council/Dockerfile
    env_file:
      - ./.env
      - ./twilight_council/.env
    volumes:
      - ./.env:/carrier/.env:ro
      - ./twilight_council:/carrier/twilight_council:rw
      - ./pylon:/carrier/pylon
    depends_on:
      - tempest
    mem_limit: 1g
    restart: unless-stopped
  probe:
    container_name: probe
    networks:
      - mothership-core
    build:
      context: .
      dockerfile: nexus/Dockerfile
    env_file:
      - ./.env
      - ./nexus/.env
    volumes:
      - ./.env:/carrier/.env:ro
      - ./nexus:/carrier/nexus:rw
      - ./pylon:/carrier/pylon
      - ./stargate:/stargate
      - ./stargate/warp_gate:/stargate/warp_gate
    depends_on:
      - tempest
      - mothership
      - high-templar
    mem_limit: 2g
    restart: unless-stopped
  disruptor:
    container_name: disruptor
    networks:
      - mothership-core
    build:
      context: .
      dockerfile: robotics_bay/Dockerfile
      args:
        API_PORT: ${API_PORT}
    env_file:
      - ./.env
      - ./robotics_bay/.env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./.env:/carrier/.env:ro
      - ./robotics_bay:/carrier/robotics_bay:rw
      - ./pylon:/carrier/pylon
      - ./stargate:/stargate
      - ./stargate/warp_gate:/stargate/warp_gate
    depends_on:
      - tempest
      - high-templar
    mem_limit: 1g
    restart: unless-stopped
  oracle:
    container_name: oracle
    networks:
      - mothership-core
    build:
      context: ./stasis_ward
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    env_file:
      - ./.env
      - ./stasis_ward/.env
    ports:
      - "${ORACLE_PORT_IN}:${ORACLE_PORT_IN}"
    volumes:
      - ./stasis_ward:/app
    depends_on:
      - disruptor
    mem_limit: 1g
    restart: no #unless-stopped
  observer:
    container_name: observer
    networks:
      - mothership-core
    build: ./robotics_facility_warps
    env_file:
      - ./.env
      - ./robotics_facility_warps/.env
    volumes:
      - ./pylon:/carrier/pylon
    depends_on:
      - tempest
    mem_limit: 1g
    restart: no #unless-stopped
  dark-templar:
    container_name: dark-templar
    networks:
      - mothership-core
    build: ./dark_shrine
    env_file:
      - ./.env
      - ./dark_shrine/.env
    volumes:
      - ./pylon:/carrier/pylon
    depends_on:
      - tempest
    mem_limit: 1g
    restart: no #unless-stopped

networks:
  mothership-core:
    name: mothership-core
    driver: bridge